### ISSUE TITLE
hardcoded entries

### ISSUE THREAD

**Issue by fossfreedom** [TheBigW/DRC#14]
Just looking at this file DRCFileTool.py - saw there were a few hardcoded "/home/tobias/.local/share..." paths

intentional?

Obviously will only work for other people call tobias ... :)

**Comment by TheBigW** [comment]
not really intentional so I changed to dump the output to tmp. It was fur debug purposes only and is not called in production-code, so in some way it was supposed to just work for 'tobias' :), but good to change anyway
