### ISSUE TITLE
dialog is too large for displays that are 768pix height or less

### ISSUE THREAD

**Issue by fossfreedom** [TheBigW/DRC#4]
the DRC dialog is too large - you cannot scroll through to the options at the bottom of the dialog

![pic](http://i.imgur.com/HnIpwhk.png)

move some options horizontally?

Or add the controls to be within a Gtk.ScrollWindow to allow scrolling?

**Comment by TheBigW** [comment]
should be better now: made the 3 areas now tabbed. Maybe that's how it shall have been from the beginning. Also gives the possibility to automatically guide users through the process (TBD :) )
