### ISSUE TITLE
suggested enhancement for setfilter

### ISSUE THREAD

**Issue by fossfreedom** [TheBigW/DRC#5]
on the setfilter tab you have to choose the drcfilter

clicking the open file button opens the folder in the main source directory.

Suggestion - open the directory to a subfolder containing the two calcfilter text files so that the user doesnt just pick a random source file?

**Comment by TheBigW** [comment]
valid point: default dir will be the cache dir folder where the filter files would be stored by default. Initially this will be empty as no filter was created (needs measurement). But makes sense in case a user stores its own filter there.
just committed the change. The filter dir is created during initial startup and set as default for the file chooser.

**Comment by fossfreedom** [comment]
saw this error in the terminal - issue?

```
(rhythmbox:25628): Gtk-CRITICAL **: gtk_radio_button_set_group: assertion '!g_slist_find (group, radio_button)' failed
Traceback (most recent call last):
  File "/home/dad/.local/share/rhythmbox/plugins/DRC/DRC_rb3compat.py", line 740, in _activate
    self._connect_func(action, None, self._connect_args)
  File "/home/dad/.local/share/rhythmbox/plugins/DRC/DRCUi.py", line 530, in show_ui
    self.initUI()
  File "/home/dad/.local/share/rhythmbox/plugins/DRC/DRCUi.py", line 184, in initUI
    self.filechooserbtn.set_filename()
TypeError: set_filename() takes exactly 2 arguments (1 given)
```

**Comment by TheBigW** [comment]
not sure: answer would have been "it works". As this is not a satisfactory answer and googeling did not give me any relief I decided rather to "fix" :).
- replaced radio button with text combo -> solves the Gtk-Critical
- removed "Save" style from the target curve file chooser solved another Gtk-warning
