### ISSUE TITLE
choosing impulse response open file doesnt appear to do anything

### ISSUE THREAD

**Issue by fossfreedom** [TheBigW/DRC#6]
clicking open on the calculate filter open impulse response dialog lets you choose (or create?) a file in a .cache folder.  Typing in a name and clicking open doesnt add the typed in text file into the impulse response edit field - it stays as "(none)"

What is supposed to happen here?

**Comment by TheBigW** [comment]
it needs an existing filter. The filter is the result of measurement + filter creation. The filter basically is an audio file containing the filter parameters in 32 bit float format.
To test I could give you one of my filters. It would probably sound strange as it does not match your speakers/room but you would hear an audible difference.

**Comment by fossfreedom** [comment]
ok - makes sense.

Maybe ship the plugin with your filter with the name "example filter" - so that users (like me!) dont get confused.

**Comment by TheBigW** [comment]
mhh default filter I would like to avoid: I could provide only my filters but it is very likely that they make the audio performance worse for the user (they are specific for my room and my speakers). That's exactly the use of the DRC: to compensate for the users individual environment and its interaction which its equipment.
Next option would be to ship with a default filer that just passes the signal without modification, which does also not make much sense....
